# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-chunks" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "a43e12834af9aa2dfa8f2eb24391b377348d1afc872d998cad731ca2d82fcb43"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b2f87e9f6e94a6cc58d00597a9b3382fd47421002fdde11237c61626aacbbc4"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1d205e3343b8daaac57fa481184030a96f4c609f6b34df3d1716cc0160345d35"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "18f5ef849cbffb4e56b2795c7cec5389979cc1a6bfbf211f18ae602091e9e4c8"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-chunks"
  desc "Commit and push changes in chunks to avoid SCM push size limits"
  homepage "https://github.com/jishnuteegala/git-chunks"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-chunks"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-chunks"]
    end
  end

  # No zap stanza required

end
