# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-chunks" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "4bf68c811c2dcec8ffbead2be59670353af51cdbefec44bd0eb03ffe9121c2c5"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "44723684873e33c20bda9c4e8ae2a1ae9b9c135e92b514170a470dcdb090f5f3"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e60a765e787fe2beb63c1b9248f42acc745af77d0227489dd58ec7137f72a069"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f79783ae41010b88e9ec0be6c97307933d7f0e99e903ab568f75b25a1e61cc37"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-chunks"
  desc "Commit and push changes in chunks to avoid SCM push size limits"
  homepage "https://github.com/jishnuteegala/git-chunks"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-chunks"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-chunks"]
    end
  end

  # No zap stanza required

end
