# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-chunks" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "63e9c72909cc9278da9dbdbab3720d5d650156a2a45175773bf10ba956de82be"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0a900b14edf637134fd0594e0afa00c3cf4cafc47522436edfbb9221595ae9e"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f2edfb4934cb9cec4444efc5187ea0b97dffb45ec1faf0c67a4bb68d17b72d8"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbd48fbf21a262654abecc19fa61d1a3703495b37ab099197711b9b564d14bbd"
      url "https://github.com/jishnuteegala/git-chunks/releases/download/v#{version}/git-chunks_#{version}_linux_arm64.tar.gz"
    end
  end

  name "git-chunks"
  desc "Commit and push changes in chunks to avoid SCM push size limits"
  homepage "https://github.com/jishnuteegala/git-chunks"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-chunks"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-chunks"]
    end
  end

  # No zap stanza required

end
